@url = "http://localhost:3000/"

//to get all users
GET http://localhost:3000/user HTTP/1.1

//to get a single user
###
GET http://localhost:3000/user/60f2cc58-411d-442a-a694-c67ab89d7c68 HTTP/1.1

//to create a new user
###
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "name": "Abike Ladele",
    "email": "abikeladele@example.com",
    "password": "passkey"
}

//to edit an existing user
###
PUT http://localhost:3000/user/60f2cc58-411d-442a-a694-c67ab89d7c68 HTTP/1.1
Content-Type: application/json

{
    "name": "Abike O. Ladele",
    "email": "abikeladele@example.com",
    "password": "passkey123"
}

//to delete a user
###
DELETE http://localhost:3000/user/60f2cc58-411d-442a-a694-c67ab89d7c68 HTTP/1.1